config/routes.rb
CarrierwaveNestedformMongoid::Application.routes.draw do
  resources :foo
  get '/upload' => 'foo#upload', :as => :upload
  post '/upload' => 'foo#update', :as => :update
  root :to => 'foo#show'
end

app/models/foo.rb
class Foo
  include Mongoid::Document

  field :title, type: String

  has_many :foo_images # Photoes of the dish
  accepts_nested_attributes_for :foo_images, :allow_destroy => true
end

app/models/foo_image.rb
class FooImage
  include Mongoid::Document

  attr_accessible :image
  mount_uploader :image, FooUploader

  belongs_to :foo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/foo_controller.rb
class FooController < ApplicationController
  def show
    @foo = Foo.first
  end

  def upload
    @foo = Foo.first_or_create
  end

  def update
    updated_foo = Foo.first
    updated_foo.update_attributes(params[:foo])
    updated_foo.save
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foo/show.html.erb
<table class="table">
  <thead><tr><th><%= @foo.title %></th></tr></thead>

  <tbody>
    <tr>
      <td>
        <% @foo.foo_images.each do |i| %>
          <a href="<%= i.image.url %>"><%= image_tag i.image.thumb.url %></a>
        <% end %>
      </td>
    </tr>
  </tbody>

  <tfoot><tr><th><%= link_to "Update", upload_path, :class => "btn btn-primary" %></th></tr></tfoot>
</table>

app/views/foo/upload.html.erb
<%= nested_form_for @foo, :html=>{:multipart => true } do |f| %>
  <fieldset>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :foo_images %>
      <%= f.fields_for :foo_images do |fi| %>
        <% if fi.object.new_record? %>
            <%= fi.file_field :image %>
        <% else %>
            <%= image_tag fi.object.image.url %>
            <%= fi.link_to_remove "Remove" %>
        <% end %>
      <% end %>
      <%= f.link_to_add "Add", :foo_images %>
    </div>

    <%= f.submit %>
  </fieldset>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CarrierwaveNestedformMongoid" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="container">
      <h2> Carriverwave test </h2>
      <%= bootstrap_flash %>
      <%= yield %>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>